version: "3"
services:
    amprobe:
        image: amuluze/amprobe:v1.3.2
        container_name: amprobe
        restart: always
        network_mode: "host"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /dev:/host/dev:ro
            - /etc:/host/etc:ro
            - /:/rootfs:ro
            - /data/amprobe/configs:/app/configs
