version: '3'
services:
    amprobe:
        image: amuluze/amprobe:v1.3.4
        container_name: amprobe
        restart: always
        volumes:
            - /data/amprobe/configs:/app/configs
            - /data/amprobe/nginx/nginx.conf:/etc/nginx/nginx.conf
            - /data/amvector/amvector.socket:/app/amvector.socket
