// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package service

import (
	api4 "github.com/amuluze/amprobe/service/audit/api"
	repository2 "github.com/amuluze/amprobe/service/audit/repository"
	service2 "github.com/amuluze/amprobe/service/audit/service"
	api3 "github.com/amuluze/amprobe/service/auth/api"
	"github.com/amuluze/amprobe/service/auth/repository"
	"github.com/amuluze/amprobe/service/auth/service"
	"github.com/amuluze/amprobe/service/container/api"
	"github.com/amuluze/amprobe/service/container/rpc"
	api2 "github.com/amuluze/amprobe/service/host/api"
	rpc2 "github.com/amuluze/amprobe/service/host/rpc"
	"github.com/amuluze/amprobe/service/model"
)

// Injectors from wire.go:

func BuildInjector(configFile string) (*Injector, func(), error) {
	config, err := NewConfig(configFile)
	if err != nil {
		return nil, nil, err
	}
	store, cleanup, err := InitAuthStore(config)
	if err != nil {
		return nil, nil, err
	}
	models := model.NewModels()
	db, err := NewDB(config, models)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	auther, cleanup2, err := InitAuth(config, store, db)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	client, err := NewRPCClient(config)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	containerService := rpc.NewContainerService(client)
	containerAPI := api.NewContainerAPI(containerService)
	hostService := rpc2.NewHostService(client)
	hostAPI := api2.NewHostAPI(hostService)
	authRepo := repository.NewAuthRepo(db)
	authService := service.NewAuthService(auther, authRepo)
	authAPI := api3.NewLoginAPI(authService)
	auditRepo := repository2.NewAuditRepo(db)
	auditService := service2.NewAuditService(auditRepo)
	auditAPI := api4.NewAuditAPI(auditService)
	loggerHandler := NewLoggerHandler()
	router := &Router{
		config:        config,
		auth:          auther,
		containerAPI:  containerAPI,
		hostAPI:       hostAPI,
		authAPI:       authAPI,
		auditAPI:      auditAPI,
		loggerHandler: loggerHandler,
	}
	app := NewFiberApp(config, router)
	prepare := &Prepare{
		db: db,
	}
	logger := NewLogger(config)
	injector, err := NewInjector(app, router, prepare, config, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	return injector, func() {
		cleanup2()
		cleanup()
	}, nil
}
