server {
    listen       80;
    listen       [::]:80;
    server_name  _; # 服务器地址或绑定域名

    ssl_certificate {{CERTS_DIR}}/minion.crt;
    ssl_certificate_key {{CERTS_DIR}}/minion.key;
    ssl_client_certificate {{CERTS_DIR}}/client_ca.crt;

    include server.conf
}
