[program:server]
command=/app/amprobe web -c /app/configs/config.toml -m /app/configs/model.conf
directory=/app
autostart=true
startsecs=10
autorestart=true
startretries=3
redirect_stderr=true
priority=20
stdout_logfile=/app/amprobe/app.log
stdout_logfile_maxbytes=200MB
stdout_logfile_backups = 10
stderr_logfile=/app/amprobe/app.log
stderr_logfile_maxbytes=200MB
stderr_logfile_backups = 10