// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package service

// Injectors from wire.go:

func BuildInjector(configFile string, prefix Prefix) (*Injector, func(), error) {
	config, err := NewConfig(configFile, prefix)
	if err != nil {
		return nil, nil, err
	}
	server, err := NewRPCServer(config)
	if err != nil {
		return nil, nil, err
	}
	logger := NewLogger(config)
	injector, err := NewInjector(config, server, logger)
	if err != nil {
		return nil, nil, err
	}
	return injector, func() {
	}, nil
}
